//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsemac.Forms.Styles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gsemac.Forms.Styles.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply style to object of type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotApplyStyleToType {
            get {
                return ResourceManager.GetString("CannotApplyStyleToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast property of type &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotCastPropertyOfTypeToType {
            get {
                return ResourceManager.GetString("CannotCastPropertyOfTypeToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot render objects of type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotRenderType {
            get {
                return ResourceManager.GetString("CannotRenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &quot;{0}&quot; was not recognized as a valid dimension..
        /// </summary>
        internal static string MalformedDimensionValue {
            get {
                return ResourceManager.GetString("MalformedDimensionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &quot;{0}&quot; is not a valid property value..
        /// </summary>
        internal static string MalformedPropertyValue {
            get {
                return ResourceManager.GetString("MalformedPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &quot;{0}&quot; cannot be parsed as &apos;{1}&apos;..
        /// </summary>
        internal static string MalformedPropertyValueAsType {
            get {
                return ResourceManager.GetString("MalformedPropertyValueAsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &quot;{0}&quot; requires {1} argument(s), but {2} were given..
        /// </summary>
        internal static string PropertyFunctionRequiresNArguments {
            get {
                return ResourceManager.GetString("PropertyFunctionRequiresNArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name cannot be empty..
        /// </summary>
        internal static string PropertyNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("PropertyNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unexpected token &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedTokenTypeWithType {
            get {
                return ResourceManager.GetString("UnexpectedTokenTypeWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit &quot;{0}&quot; cannot be converted to degrees..
        /// </summary>
        internal static string UnitCannotBeConvertedToDegreesWithUnit {
            get {
                return ResourceManager.GetString("UnitCannotBeConvertedToDegreesWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit &quot;{0}&quot; cannot be converted to pixels..
        /// </summary>
        internal static string UnitCannotBeConvertedToPixelsWithUnit {
            get {
                return ResourceManager.GetString("UnitCannotBeConvertedToPixelsWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &quot;{0}&quot; was not recognized as a valid property..
        /// </summary>
        internal static string UnrecognizedProperty {
            get {
                return ResourceManager.GetString("UnrecognizedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &quot;{0}&quot; was not recognized as a valid unit..
        /// </summary>
        internal static string UnrecognizedUnits {
            get {
                return ResourceManager.GetString("UnrecognizedUnits", resourceCulture);
            }
        }
    }
}
