//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsemac.Forms.Styles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gsemac.Forms.Styles.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply style to object of type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotApplyStyleToType {
            get {
                return ResourceManager.GetString("CannotApplyStyleToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast property of type &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string CannotCastPropertyOfTypeToType {
            get {
                return ResourceManager.GetString("CannotCastPropertyOfTypeToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert objects of type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotConvertObjectsOfType {
            get {
                return ResourceManager.GetString("CannotConvertObjectsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot render objects of type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotRenderType {
            get {
                return ResourceManager.GetString("CannotRenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not match the type of the given object (&apos;{1}&apos;)..
        /// </summary>
        internal static string GivenTypeDoesNotMatchValueType {
            get {
                return ResourceManager.GetString("GivenTypeDoesNotMatchValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; does not represent a valid dimension..
        /// </summary>
        internal static string InvalidDimension {
            get {
                return ResourceManager.GetString("InvalidDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create property &quot;{0}&quot; with the given arguments..
        /// </summary>
        internal static string InvalidPropertyArguments {
            get {
                return ResourceManager.GetString("InvalidPropertyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; is not a valid property name..
        /// </summary>
        internal static string InvalidPropertyName {
            get {
                return ResourceManager.GetString("InvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; is not a valid property value..
        /// </summary>
        internal static string InvalidPropertyValue {
            get {
                return ResourceManager.GetString("InvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; is not a valid unit..
        /// </summary>
        internal static string InvalidUnit {
            get {
                return ResourceManager.GetString("InvalidUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; is not a valid variable name..
        /// </summary>
        internal static string InvalidVariableName {
            get {
                return ResourceManager.GetString("InvalidVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse string &apos;{0}&apos; as type &apos;{1}&apos;..
        /// </summary>
        internal static string MalformedPropertyValueAsType {
            get {
                return ResourceManager.GetString("MalformedPropertyValueAsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; requires {1} argument(s), but {2} were given..
        /// </summary>
        internal static string PropertyFunctionRequiresNArguments {
            get {
                return ResourceManager.GetString("PropertyFunctionRequiresNArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name cannot be empty..
        /// </summary>
        internal static string PropertyNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("PropertyNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unexpected token &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit &apos;{0}&apos; cannot be converted to degrees..
        /// </summary>
        internal static string UnitCannotBeConvertedToDegrees {
            get {
                return ResourceManager.GetString("UnitCannotBeConvertedToDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit &quot;{0}&quot; cannot be converted to pixels..
        /// </summary>
        internal static string UnitCannotBeConvertedToPixels {
            get {
                return ResourceManager.GetString("UnitCannotBeConvertedToPixels", resourceCulture);
            }
        }
    }
}
